function f2 = f2_rcom_constrained_z_0_9(x,z)
%F2_RCOM_CONSTRAINED_Z_0_9
%    F2 = F2_RCOM_CONSTRAINED_Z_0_9(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:59:10
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*1.993708494899422e-1-8.350737104134194e-1;
t3 = x2.*(2.0./5.0)-9.0./1.0e1;
t4 = x1.*5.981125484698266e-1;
t5 = t4+3.987416989798844e-1;
t6 = x1.*4.755396264171111e-2;
t7 = t6+3.170264176114074e-2;
t8 = x1.*(-2.158513208805704e-1)+(t7.*(t4-(t5.*(t6+1.313880665061118e-1))./t7+2.908160385395992e-1))./(t5.*6.0)+8.394848819554579e-1;
f2 = t2.^2./3.0+t3.^2./3.0+t8.^2./3.0;

