function f2 = f2_rcom_constrained_z_0_1(x,z)
%F2_RCOM_CONSTRAINED_Z_0_1
%    F2 = F2_RCOM_CONSTRAINED_Z_0_1(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:57:47
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*1.521850561306759e-1-8.760239545095365e-1;
t3 = x2.*(2.0./5.0)-9.0./1.0e1;
t4 = x1.*4.565551683920277e-1;
t5 = x1.*3.893037094795364e-1;
t6 = t5+2.595358063196909e-1;
t7 = t4+3.043701122613518e-1;
t8 = x1.*(-3.297679031598455e-1)+(t6.*(t4-(t7.*(t5+3.356283343850289e-1))./t6+1.394861606814291e-1))./(t7.*6.0)+7.6747264321588e-1;
f2 = t2.^2./3.0+t3.^2./3.0+t8.^2./3.0;

