function f2 = f2_rcom_constrained_z_0(x,z)
%F2_RCOM_CONSTRAINED_Z_0
%    F2 = F2_RCOM_CONSTRAINED_Z_0(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:57:33
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*1.415627068593044e-1-8.840648507766279e-1;
t3 = x2.*(2.0./5.0)-9.0./1.0e1;
t4 = x1.*4.246881205779131e-1;
t5 = t4+2.831254137186087e-1;
t6 = x1.*4.238395925819106e-1;
t7 = t6+2.825597283879404e-1;
t8 = x1.*(-3.412798641939702e-1)+(t7.*(t4-(t5.*(t6+3.533410818175926e-1))./t7+1.124854816216236e-1))./(t5.*6.0)+7.606831982990778e-1;
f2 = t2.^2./3.0+t3.^2./3.0+t8.^2./3.0;

