function f2 = f2_rcom_constrained_z_1(x,z)
%F2_RCOM_CONSTRAINED_Z_1
%    F2 = F2_RCOM_CONSTRAINED_Z_1(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:59:20
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*1.999999000000083e-1-8.333500666638833e-1;
t3 = x2.*(2.0./5.0)-9.0./1.0e1;
t4 = x1.*5.99999700000025e-1;
t5 = t4+3.999998000000167e-1;
t6 = x1.*5.999998999999756e-4;
t7 = t6+3.999999333333171e-4;
t8 = x1.*(-2.001999999666667e-1)+(t7.*(t4-(t5.*(t6+1.003999499333375e-1))./t7+2.998998000166833e-1))./(t5.*6.0)+8.498666750222215e-1;
f2 = t2.^2./3.0+t3.^2./3.0+t8.^2./3.0;

