function f2 = f2_rcom_constrained_z_0_3(x,z)
%F2_RCOM_CONSTRAINED_Z_0_3
%    F2 = F2_RCOM_CONSTRAINED_Z_0_3(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:58:09
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*5.117094573379158e-1;
t3 = x1.*3.132944801156505e-1;
t4 = t3+2.08862986743767e-1;
t5 = t2+3.411396382252772e-1;
t6 = x1.*(-3.044314933718835e-1)+(t4.*(t2-(t5.*(t3+2.941478963000863e-1))./t4+1.889238915393354e-1))./(t5.*6.0)+7.828315194926911e-1;
t7 = x1.*1.705698191126386e-1-8.616560783725646e-1;
t8 = x2.*(2.0./5.0)-9.0./1.0e1;
f2 = t6.^2./3.0+t7.^2./3.0+t8.^2./3.0;

