function hess = ZDT1_fhtest_f2_hess(in1,z1)
%ZDT1_FHTEST_F2_HESS
%    HESS = ZDT1_FHTEST_F2_HESS(IN1,Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-Apr-2020 22:29:15

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x2.*9.0;
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = t4.*x1;
t6 = 1.0./t5.^(3.0./2.0);
t7 = 1.0./t3.^2;
hess = reshape([(t4.*t6)./4.0e1,t6.*t7.*x1.*(-9.0./4.0e1),0.0,t6.*t7.*x1.*(-9.0./4.0e1),1.0./t3.^3.*t6.*x1.^2.*(8.1e1./4.0e1),0.0,0.0,0.0,0.0],[3,3]);
