function f2 = f2_rcom_unconstrained(x,z)
%F2_RCOM_UNCONSTRAINED
%    F2 = F2_RCOM_UNCONSTRAINED(X1,X2,Z1)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:59:40
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';
z1 = z(1, :).';

% Original content from Symbolic Math Toolbox
t2 = x2.*(2.0./5.0)-9.0./1.0e1;
t3 = conj(z1);
t4 = t3.*7.833981633974483e-1;
t5 = t4+7.863981633974483e-1;
t7 = sin(t5);
t8 = cos(t5);
t9 = x1.*(3.0./5.0);
t10 = t9+2.0./5.0;
t6 = t8./6.0e1-(t7.*t10)./3.0+2.9e1./3.0e1;
t11 = t7./6.0e1+x1./5.0+(t8.*t10)./3.0+(t8.*(t8./1.0e1-t7.*t10+(t7.*(t7./1.0e1+t8.*t10))./t8+1.0./1.0e1))./(t7.*6.0)-1.3e1./1.5e1;
f2 = t2.^2./3.0+t6.^2./3.0+t11.^2./3.0;

