function f2 = f2_rcom_constrained_z_0_4(x,z)
%F2_RCOM_CONSTRAINED_Z_0_4
%    F2 = F2_RCOM_CONSTRAINED_Z_0_4(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:58:19
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*5.34658382680548e-1;
t3 = x1.*2.722873736136523e-1;
t4 = t2+3.56438921787032e-1;
t5 = t3+1.815249157424349e-1;
t6 = x1.*(-2.907624578712174e-1)+(t5.*(t2-(t4.*(t3+2.706346461891929e-1))./t5+2.110576928514233e-1))./(t4.*6.0)+7.91306739678062e-1;
t7 = x1.*1.78219460893516e-1-8.554172308935908e-1;
t8 = x2.*(2.0./5.0)-9.0./1.0e1;
f2 = t6.^2./3.0+t7.^2./3.0+t8.^2./3.0;

