function f2 = f2_rcom_constrained_z_0_7(x,z)
%F2_RCOM_CONSTRAINED_Z_0_7
%    F2 = F2_RCOM_CONSTRAINED_Z_0_7(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:58:50
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*5.83365878679019e-1;
t3 = x1.*1.403005758828382e-1;
t4 = t3+9.353371725522548e-2;
t5 = t2+3.889105857860127e-1;
t6 = x1.*(-2.467668586276127e-1)+(t4.*(t2-(t5.*(t3+1.907613637017286e-1))./t4+2.655271564722063e-1))./(t5.*6.0)+8.19284153173841e-1;
t7 = x2.*(2.0./5.0)-9.0./1.0e1;
t8 = x1.*1.944552928930063e-1-8.409270429569635e-1;
f2 = t6.^2./3.0+t7.^2./3.0+t8.^2./3.0;

