function f2 = f2_rcom_constrained_z_0_6(x,z)
%F2_RCOM_CONSTRAINED_Z_0_6
%    F2 = F2_RCOM_CONSTRAINED_Z_0_6(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 23:58:39
% Includes scripted file modifications (LBracket.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*1.901989387751121e-1-8.450208274748686e-1;
t3 = x2.*(2.0./5.0)-9.0./1.0e1;
t4 = x1.*5.705968163253362e-1;
t5 = x1.*1.855243196979591e-1;
t6 = t5+1.236828797986394e-1;
t7 = t4+3.803978775502241e-1;
t8 = x1.*(-2.618414398993197e-1)+(t6.*(t4-(t7.*(t5+2.187823491861954e-1))./t6+2.494771576005643e-1))./(t7.*6.0)+8.095891285025275e-1;
f2 = t2.^2./3.0+t3.^2./3.0+t8.^2./3.0;

