function fHandle = Schulz_Lamp_Mass(in1)
%SCHULZ_LAMP_MASS
%    FHANDLE = SCHULZ_LAMP_MASS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-May-2020 20:39:23

%Automatically generated by Schulz_Lamp.createProblem()
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
x15 = in1(15,:);
x16 = in1(16,:);
x17 = in1(17,:);
x18 = in1(18,:);
x19 = in1(19,:);
x20 = in1(20,:);
x21 = in1(21,:);
fHandle = sqrt(abs(x8).^2.*4.0+abs(x7.*2.0-2.0).^2+abs(x9.*2.0+2.0).^2).*6.452591373060889e-2+sqrt(abs(x10).^2.*4.0+abs(x11.*2.0-2.0).^2+abs(x12.*2.0+2.0).^2).*6.452591373060889e-2+sqrt(abs(x15-2.0).^2+abs(x13.*(3.0./5.0)+2.0./5.0).^2+abs(x14.*(3.0./5.0)+2.0./5.0).^2).*6.452591373060889e-2+sqrt(abs(x18-2.0).^2+abs(x16.*(3.0./5.0)-1.0).^2+abs(x17.*(3.0./5.0)+2.0./5.0).^2).*6.452591373060889e-2+sqrt(abs(x21-2.0).^2+abs(x20.*(3.0./5.0)-1.0).^2+abs(x19.*(3.0./5.0)+2.0./5.0).^2).*6.452591373060889e-2+sqrt(abs(x1).^2.*4.0+abs(x2).^2.*4.0+abs(x3.*2.0+2.0).^2).*6.452591373060889e-2+sqrt(abs(x4).^2.*4.0+abs(x5).^2.*4.0+abs(x6.*2.0+2.0).^2).*6.452591373060889e-2-7.386112020952258e-1;
