function fHandle = Schulz_Turbine_Mass(in1)
%SCHULZ_TURBINE_MASS
%    FHANDLE = SCHULZ_TURBINE_MASS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Aug-2020 10:48:27

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
fHandle = ((x2.*9.0+6.0).*(x1.*6.0e1+4.0e1).*8.4678717818753e-3)./(pi.*(x3.*1.5e1+5.0))-1.078162836318169e-2;
