function fHandle = Schulz_Turbine_Power(in1)
%SCHULZ_TURBINE_POWER
%    FHANDLE = SCHULZ_TURBINE_POWER(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Aug-2020 10:48:27

x1 = in1(1,:);
t3 = x1.*6.0e1;
t2 = t3+4.0e1;
t4 = t2.^2;
t5 = pi.^2;
t6 = t5.^2;
t7 = t4.^2;
fHandle = t4.*pi.*(t2.*pi.*(-7.959384869851941e-4)+t4.*t5.*1.213158136939615e-5-t6.*t7.*2.927015234074743e-10+t2.*t4.*t5.*pi.*1.419900971480346e-8+t2.*t6.*t7.*pi.*6.679062333736464e-13-t4.*t5.*t6.*t7.*4.490541736071033e-16+8.047179751417449e-3).*(-1.824614744559419e-4)+9.742986779995344e-1;
