function fHandle = Turbine_Lift(x,z)
%TURBINE_LIFT
%    FHANDLE = TURBINE_LIFT(X1,X2,X3,Z1)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-May-2020 16:46:02
% Includes scripted file modifications (Turbine.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';
x3 = x(3, :).';
z1 = z(1, :).';

% Original content from Symbolic Math Toolbox
t2 = z1.*2.0+4.0;
fHandle = (t2.^2.*(x2.*9.0+6.0).*(x1.*6.0e1+4.0e1).*2.961504391581957e-4)./(pi.*(x3.*1.5e1+5.0))-1.809939861717488e-2;

