function fHandle = Lamp_Focal_Point(in1,z1)
%LAMP_FOCAL_POINT
%    FHANDLE = LAMP_FOCAL_POINT(IN1,Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Jan-2021 00:26:08

%Automatically generated by Lamp.createProblem()
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
x15 = in1(15,:);
x16 = in1(16,:);
x17 = in1(17,:);
x18 = in1(18,:);
x19 = in1(19,:);
x20 = in1(20,:);
x21 = in1(21,:);
t5 = x3.*1.2e1;
t6 = z1.*1.6e1;
t2 = abs(t5-t6+x9.*2.0+x18);
t8 = x1.*4.0;
t3 = abs(t8+x7.*2.0+x16.*(3.0./5.0)-1.1e1);
t10 = x2.*4.0;
t4 = abs(t10+x8.*2.0+x17.*(3.0./5.0)-3.8e1./5.0);
t7 = abs(t5-t6+x6.*2.0+x15);
t9 = abs(t8+x4.*2.0+x13.*(3.0./5.0)-3.8e1./5.0);
t11 = abs(t10+x5.*2.0+x14.*(3.0./5.0)-3.8e1./5.0);
t12 = abs(t5-t6+x12.*2.0+x21);
t13 = abs(t10+x11.*2.0+x20.*(3.0./5.0)-1.1e1);
t14 = abs(t8+x10.*2.0+x19.*(3.0./5.0)-3.8e1./5.0);
fHandle = sqrt(t2.^2+t3.^2+t4.^2)./6.0e1+sqrt(t7.^2+t9.^2+t11.^2)./6.0e1+sqrt(t12.^2+t13.^2+t14.^2)./6.0e1;
