function fHandle = ZDT1_fhtest_f2(x,z)
%ZDT1_FHTEST_F2
%    FHANDLE = ZDT1_FHTEST_F2(X1,X2)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-Apr-2020 22:29:15
% Includes scripted file modifications (ZDT1_fhtest.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
t2 = x2.*9.0;
t3 = t2+1.0;
fHandle = t3.*(sqrt(x1./t3)-1.0).*(-1.0./1.0e1);

