function fHandle = ZDT1_fhtest_f1(x,z)
%ZDT1_FHTEST_F1
%    FHANDLE = ZDT1_FHTEST_F1(X1)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-Apr-2020 22:29:14
% Includes scripted file modifications (ZDT1_fhtest.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';

% Original content from Symbolic Math Toolbox
fHandle = x1;

