function hess = ZDT1_fhtest_f1_hess(in1,z1)
%ZDT1_FHTEST_F1_HESS
%    HESS = ZDT1_FHTEST_F1_HESS(IN1,Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-Apr-2020 22:29:15

x1 = in1(1,:);
x2 = in1(2,:);
hess = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
