function deriv = ZDT1_fhtest_deriv(in1,z1)
%ZDT1_FHTEST_DERIV
%    DERIV = ZDT1_FHTEST_DERIV(IN1,Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    07-Apr-2020 22:29:15

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x2.*9.0;
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = t4.*x1;
t6 = 1.0./sqrt(t5);
deriv = reshape([1.0,t6.*(-1.0./2.0e1),0.0,sqrt(t5).*(-9.0./1.0e1)+t4.*t6.*x1.*(9.0./2.0e1)+9.0./1.0e1,0.0,0.0],[2,3]);
