function fHandle = Turbine_Power(x,z)
%TURBINE_POWER
%    FHANDLE = TURBINE_POWER(X1,Z1)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Aug-2021 18:15:11
% Includes scripted file modifications (Turbine.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';
x3 = x(3, :).';
z1 = z(1, :).';

% Original content from Symbolic Math Toolbox
t5 = x1.*6.0e1;
t2 = t5+4.0e1;
t7 = z1.*2.0;
t3 = t7+4.0;
t4 = t3.^2;
t6 = t2.^2;
t8 = pi.^2;
t9 = t8.^2;
t10 = t6.^2;
fHandle = t3.*t4.*t6.*pi.*(1.0./t3.^2.*t6.*t8.*4.223003474686798e-4-1.0./t3.^4.*t9.*t10.*3.546770024378316e-7-(t2.*pi.*4.696037073212645e-3)./t3-1.0./t3.^6.*t6.*t8.*t9.*t10.*1.894134467646587e-11+t2.*1.0./t3.^3.*t6.*t8.*pi.*2.916178416216619e-6+t2.*1.0./t3.^5.*t9.*t10.*pi.*4.775023956923846e-9+8.047179751417449e-3).*(-8.884134914277596e-7)+9.742986779995344e-1;

