function fHandle = Turbine_RadiusPenalty(x,z)
%TURBINE_RADIUSPENALTY
%    FHANDLE = TURBINE_RADIUSPENALTY(X1)
%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Mar-2020 20:11:13
% Includes scripted file modifications (Turbine.fixFileInputs) to match system specs

% unpack the block vars into the variable names used by the function
x1 = x(1, :).';
x2 = x(2, :).';
x3 = x(3, :).';
z1 = z(1, :).';

% Original content from Symbolic Math Toolbox
t2 = x1.*6.0e1+4.0e1;
t3 = t2.^2;
fHandle = (t2.*t3)./9.36e5-8.0./1.17e2;

